service:
  name: npm_package_name
  description: npm_package_description
  baseUrl: /api/oversea-ordering
  docsBaseUrl: /docs/oversea-ordering

server:
  host: SERVER_HOST
  port: SERVER_PORT
  hostname: SERVER_HOSTNAME
  swaggerSchema: SWAGGER_SCHEMA

client:
  host: CLIENT_HOST

firebase:
  projectId: FIREBASE_PROJECT_ID
  privateKey: FIREBASE_PRIVATE_KEY
  clientEmail: FIREBASE_CLIENT_EMAIL

oauth:
  google:
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  facebook:
    apiUrl: FACEBOOK_API_URL
    clientId: FACEBOOK_CLIENT_ID
    clientSecret: FACEBOOK_CLIENT_SECRET

jwtPrivateKey: JWT_PRIVATE_KEY

mongodb:
  uri: MONGODB_URI

tmApiToken: TM_API_TOKEN

rapidApiToken: RAPID_API_TOKEN

vnpay:
  merchantCode: MERCHANT_CODE
  hash: MERCHANT_HASH
  endpoint: VNP_ENDPOINT
  returnUrl: VNP_RETURN_URL

mail:
  apiKey: MAILJET_API_KEY
  secretKey: MAILJET_SECRET_KEY

orderTimeoutInMinutes: ORDER_TIMEOUT_IN_MINUTES
